"""create correction requests table

Revision ID: 504b2f31813e
Revises: e291a8a0f066
Create Date: 2026-09-24 18:24:34.398798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '504b2f31813e'
down_revision: Union[str, Sequence[str], None] = 'e291a8a0f066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correction_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_attendance_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('requested_status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('request_status', sa.String(length=20), nullable=False),
    sa.Column('reviewer_remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_attendance_id'], ['student_attendance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correction_requests_id'), 'correction_requests', ['id'], unique=False)
    op.create_index(op.f('ix_correction_requests_requested_by'), 'correction_requests', ['requested_by'], unique=False)
    op.create_index(op.f('ix_correction_requests_reviewed_by'), 'correction_requests', ['reviewed_by'], unique=False)
    op.create_index(op.f('ix_correction_requests_student_attendance_id'), 'correction_requests', ['student_attendance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_correction_requests_student_attendance_id'), table_name='correction_requests')
    op.drop_index(op.f('ix_correction_requests_reviewed_by'), table_name='correction_requests')
    op.drop_index(op.f('ix_correction_requests_requested_by'), table_name='correction_requests')
    op.drop_index(op.f('ix_correction_requests_id'), table_name='correction_requests')
    op.drop_table('correction_requests')
    # ### end Alembic commands ###
