"""create academic terms table

Revision ID: 8d3d22fd3a24
Revises: 472a75e02a4d
Create Date: 2026-09-24 17:04:58.788128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d3d22fd3a24'
down_revision: Union[str, Sequence[str], None] = '472a75e02a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('semester', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_terms_academic_year'), 'academic_terms', ['academic_year'], unique=False)
    op.create_index(op.f('ix_academic_terms_id'), 'academic_terms', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_academic_terms_id'), table_name='academic_terms')
    op.drop_index(op.f('ix_academic_terms_academic_year'), table_name='academic_terms')
    op.drop_table('academic_terms')
    # ### end Alembic commands ###
