"""create programs table

Revision ID: 99d3dd27b21f
Revises: 8d3d22fd3a24
Create Date: 2026-09-24 17:08:09.433633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99d3dd27b21f'
down_revision: Union[str, Sequence[str], None] = '8d3d22fd3a24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_code'), 'programs', ['code'], unique=True)
    op.create_index(op.f('ix_programs_department_id'), 'programs', ['department_id'], unique=False)
    op.create_index(op.f('ix_programs_id'), 'programs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_programs_id'), table_name='programs')
    op.drop_index(op.f('ix_programs_department_id'), table_name='programs')
    op.drop_index(op.f('ix_programs_code'), table_name='programs')
    op.drop_table('programs')
    # ### end Alembic commands ###
