"""create student enrollments table

Revision ID: b334d8e39742
Revises: dfa13bfbb6ba
Create Date: 2026-09-24 18:12:41.310515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b334d8e39742'
down_revision: Union[str, Sequence[str], None] = 'dfa13bfbb6ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('academic_term_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academic_term_id'], ['academic_terms.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'subject_id', 'section_id', 'academic_term_id', name='uq_student_enrollment')
    )
    op.create_index(op.f('ix_student_enrollments_academic_term_id'), 'student_enrollments', ['academic_term_id'], unique=False)
    op.create_index(op.f('ix_student_enrollments_id'), 'student_enrollments', ['id'], unique=False)
    op.create_index(op.f('ix_student_enrollments_section_id'), 'student_enrollments', ['section_id'], unique=False)
    op.create_index(op.f('ix_student_enrollments_student_id'), 'student_enrollments', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_enrollments_subject_id'), 'student_enrollments', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_enrollments_subject_id'), table_name='student_enrollments')
    op.drop_index(op.f('ix_student_enrollments_student_id'), table_name='student_enrollments')
    op.drop_index(op.f('ix_student_enrollments_section_id'), table_name='student_enrollments')
    op.drop_index(op.f('ix_student_enrollments_id'), table_name='student_enrollments')
    op.drop_index(op.f('ix_student_enrollments_academic_term_id'), table_name='student_enrollments')
    op.drop_table('student_enrollments')
    # ### end Alembic commands ###
