"""create faculty assignments table

Revision ID: dfa13bfbb6ba
Revises: cf2ccd3182e2
Create Date: 2026-09-24 17:35:58.019424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfa13bfbb6ba'
down_revision: Union[str, Sequence[str], None] = 'cf2ccd3182e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('academic_term_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academic_term_id'], ['academic_terms.id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faculty_id', 'subject_id', 'section_id', 'academic_term_id', name='uq_faculty_assignment')
    )
    op.create_index(op.f('ix_faculty_assignments_academic_term_id'), 'faculty_assignments', ['academic_term_id'], unique=False)
    op.create_index(op.f('ix_faculty_assignments_faculty_id'), 'faculty_assignments', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_faculty_assignments_id'), 'faculty_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_faculty_assignments_section_id'), 'faculty_assignments', ['section_id'], unique=False)
    op.create_index(op.f('ix_faculty_assignments_subject_id'), 'faculty_assignments', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faculty_assignments_subject_id'), table_name='faculty_assignments')
    op.drop_index(op.f('ix_faculty_assignments_section_id'), table_name='faculty_assignments')
    op.drop_index(op.f('ix_faculty_assignments_id'), table_name='faculty_assignments')
    op.drop_index(op.f('ix_faculty_assignments_faculty_id'), table_name='faculty_assignments')
    op.drop_index(op.f('ix_faculty_assignments_academic_term_id'), table_name='faculty_assignments')
    op.drop_table('faculty_assignments')
    # ### end Alembic commands ###
